### PR TITLE
Added the Featured Causes Panel - used slick slider included new font…

### PR DESCRIPTION
**Pull request by rimpey**
@lili2311

PIMP-74
Added the Featured Causes Panel - used slick slider included new fonts directory added new images for slider content with slider styling

screen shot 2016-03-10 at 00 03 24

### CODE REVIEW

**Comment by lili2311** [comment]
- This is going to take some time the commit is huge, can you please put all the js files into 1? Each js file is a separate download during page load. It should be all in 1 file ideally, is there any specific reason why it is multiple files?
- This could be done in much less code in just css, example: https://codepen.io/dudleystorey/pen/ehKpi, http://codepen.io/hw/pen/biEBz we need to be considerate to the page load with all the images and resources each page has to download.  Why was it js over css?
- Please keep the commits smaller, it is hard to review 20 files :scream: 
- The sliders should automatically go to the next image, timed & on click. (this can be a later improvement, but example above have all the code for all of this)

**Comment by rimpey** [comment]
- I've only modified a few files the rest are just added files this is a small commit
- all script files are put into the one script.js file on grunt deploy
- the slick slider is a fully featured, highly responsive and configurable mobile first slider very good for our purposes. I can easily add in the timer event and will change it

**Comment by lili2311** [comment]
Honestly 2k lines of  jquery code for a slider is way too much, when this can be done in 20 lines of css. I would much prefer this to be css only it is only like 20-40 lines of css max, what we can do is change this later however. The slider currently will NOT work with javascript turned off. With css that would still work.

:+1:  but will definitely revisit this especially if the site load times on mobile are not OK.

What about the dependency?

**Comment by rimpey** [comment]
Actually just noticed it doesn't have the slick dependancy so I'll change this first, along with the timer event. As for grunt-sass it is faster than the grunt-contrib-sass so I replaced it.

**Comment by lili2311** [comment]
okay fair enough

**Pull request merged**
