### PR TITLE
PIMP-75 'Have You Seen' Panel with summary tiles

### PR DESCRIPTION
**Pull request by rimpey**
Front End: @lili2311 @jj

Jira Ticket: PIMP-75
https://womenhackfornonprofits.atlassian.net/browse/PIMP-75

Description of task completed:
Summary Panel images and overlay titles with hover and click event to expose summary information using mix-in for smaller triangles - css3 transitions to manage hover and javascript to manage click event. Panel is also designed responsively.

Github Pages Link:
http://womenhackfornonprofits.github.io/pimpmycause-rebuild/

pimp-75_desktop-hover

pimp-75_mobile

### CODE REVIEW

**Comment by lili2311** [comment]
@rimpey i think these are meant to be links again that take you to the relevant pages, please change them to be clickable?

**Comment by rimpey** [comment]
Hi @lili2311   for the purposes of this Jira task I have completed layout and behaviour as specified. On click functionality is not detailed further than that, why would these panels have a click to a page? Where is this functionality defined? They are just information panels aren't they? And to which pages would they click through to, the pages don't exist yet this can be included in another Jira task. Best to keep the Jira tasks small and contained as discussed. So it's all good to go for PIMP-75 and any extra functionality on top can be put into a new Jira task and included in the next sprint :)

**Comment by lili2311** [comment]
The page links for now can be #, until the relevant pages are added, Yes of course it can be a separate ticket but it has to be created now so we don't forget. Please raise a Jira ticket under the Homepage and link it here. The same for the other PR with tiles please.

**Comment by rimpey** [comment]
Hi @lili2311 I don't know what the specifics are on the functionality of the tiles or cubes so at the stage I am unable to fill out any extra Jira tasks until I have established required behaviour according to Pimps requirements. Thanks Rhonda

**Pull request merged**
