### PR TITLE
Fixed button issue, removed 100% width

### PR DESCRIPTION
**Pull request by lili2311**
@rimpey
### [PIMP-218](https://womenhackfornonprofits.atlassian.net/browse/PIMP-218)

Fixed button issue, button was displaying 100% of container.
Issue Before:
screen shot 2016-02-28 at 15 55 52

Now:
screen shot 2016-02-28 at 15 56 29

### CODE REVIEW

**Comment by rimpey** [comment]
Hello Lili, 
Do we have any wireframes for the Log-in page I'm not sure what to compare this page to?
Thank you 
Rhonda

**Comment by rimpey** [comment]
Hello @lili2311 

https://drive.google.com/drive/u/0/folders/0Bw1aIZcuiBCXUUJ0cGhuWk5YMjA

What about the social icons and buttons at the top for the Login form?

Thanks
Rhonda

**Comment by lili2311** [comment]
As mentioned already in Jira and in slack, social buttons are not part of this PR. They will be done later on if when we have backend support for those. They may not be part of the MVP. Neither Register or Login will have social options.

**Comment by rimpey** [comment]
okay :+1:

**Pull request merged**
